# Generated by Django 4.1.1 on 2022-10-23 13:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gisdata',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='gisdata',
            name='gis_data_key',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Gis Data Key'),
        ),
        migrations.AlterField(
            model_name='gisdata',
            name='gis_data_type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Gis Data Type'),
        ),
        migrations.AlterField(
            model_name='gisdata',
            name='tags',
            field=models.TextField(blank=True, null=True, verbose_name='Tags'),
        ),
    ]
