# Generated by Django 4.1.1 on 2022-10-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_gisdata_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gisdata',
            name='description',
        ),
        migrations.AddField(
            model_name='gisdata',
            name='metadata',
            field=models.TextField(blank=True, null=True, verbose_name='Metadata'),
        ),
        migrations.AddField(
            model_name='gisdata',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED')], default='PENDING', max_length=100, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='gisdata',
            name='category',
            field=models.CharField(choices=[('GIS', 'GIS')], default='GIS', max_length=100, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='gisdata',
            name='gis_data_key',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='S3 Data Key'),
        ),
    ]
