# Generated by Django 4.1.1 on 2022-10-31 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_gisdata_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='gisdata',
            name='data_projection',
            field=models.CharField(default='EPSG:4326', max_length=100, verbose_name='Projection System'),
        ),
    ]
