# Generated by Django 4.1.1 on 2022-10-31 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_gisdata_data_projection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gisdata',
            name='category',
            field=models.CharField(blank=True, choices=[('GIS', 'GIS')], default='GIS', max_length=100, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='gisdata',
            name='data_projection',
            field=models.CharField(blank=True, default='EPSG:4326', max_length=100, verbose_name='Projection System'),
        ),
    ]
