# Generated by Django 4.1.1 on 2022-11-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_gisdata_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gisdata',
            name='attribution',
            field=models.TextField(blank=True, null=True, verbose_name='Attribution'),
        ),
        migrations.AddField(
            model_name='gisdata',
            name='img_icon_url',
            field=models.CharField(blank=True, choices=[('CSV', 'https://upload.wikimedia.org/wikipedia/commons/c/c6/.csv_icon.svg'), ('EXCEL', ''), ('SHAPEFILE', ''), ('PNG', ''), ('JPEG', ''), ('JPG', ''), ('DBF', ''), ('PRJ', ''), ('SBN', ''), ('SBX', ''), ('SHX', ''), ('CPG', ''), ('GEOTIFF', ''), ('GEOJSON', ''), ('PDF', ''), ('ZIPFILE', ''), ('7ZIP', ''), ('GZ', ''), ('RAR FILE', '')], default='', max_length=1000, verbose_name='Icon Url'),
        ),
        migrations.AddField(
            model_name='gisdata',
            name='license',
            field=models.TextField(blank=True, null=True, verbose_name='License'),
        ),
        migrations.AddField(
            model_name='gisdata',
            name='organization',
            field=models.TextField(blank=True, null=True, verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='gisdata',
            name='spatial_extent',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Spatial Extent'),
        ),
        migrations.AlterField(
            model_name='gisdata',
            name='title',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Title'),
        ),
    ]
