# Generated by Django 4.1.1 on 2022-11-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_gisdata_attribution_gisdata_img_icon_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gisdata',
            name='attribution',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Attribution'),
        ),
        migrations.AlterField(
            model_name='gisdata',
            name='organization',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Organization'),
        ),
    ]
