# Generated by Django 4.1.1 on 2022-11-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_gisdata_img_icon_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gisdata',
            name='spatial_extent',
            field=models.CharField(blank=True, default='No Spatial Extent Specified!', max_length=100, null=True, verbose_name='Spatial Extent'),
        ),
    ]
