# Generated by Django 4.1.1 on 2022-11-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_gisdata_img_icon_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gisdata',
            name='gis_data_type',
            field=models.CharField(blank=True, choices=[('Vector', 'Vector'), ('Raster', 'Raster'), ('Not Specified', 'Not Specified')], default='Not Specified', max_length=200, null=True, verbose_name='Gis Data Type'),
        ),
    ]
