# Generated by Django 4.1.1 on 2022-11-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_gisdata_gis_data_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gisdata',
            name='category',
            field=models.CharField(blank=True, choices=[('Gis', 'Gis'), ('Humanitarian', 'Humanitarian'), ('Climate Change', 'Climate Change'), ('Social Life', 'Social Life'), ('Society', 'Society'), ('Remote Sensing', 'Remote Sensing'), ('Research', 'Research'), ('Economy', 'Economy'), ('Demography', 'Demography'), ('Other', 'Other')], default='GIS', max_length=100, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='gisdata',
            name='gis_data_type',
            field=models.CharField(blank=True, choices=[('Vector', 'Vector'), ('Raster', 'Raster'), ('Other', 'Other')], default='Other', max_length=200, null=True, verbose_name='Gis Data Type'),
        ),
        migrations.AlterField(
            model_name='gisdata',
            name='img_icon_url',
            field=models.CharField(blank=True, choices=[('https://cdn-icons-png.flaticon.com/512/28/28814.png', 'ZIPFILE'), ('https://upload.wikimedia.org/wikipedia/commons/c/c6/.csv_icon.svg', 'CSV'), ('https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Microsoft_Excel_Logo_%282013-2019%29.svg/192px-Microsoft_Excel_Logo_%282013-2019%29.svg.png?20180217032706', 'EXCEL'), ('https://cdn-icons-png.flaticon.com/512/136/136443.png', 'JSON'), ('https://img.favpng.com/0/9/8/south-sumatra-west-sumatra-map-shapefile-png-favpng-qUCpKZdccecDaDJcJVn0NdFZS.jpg', 'SHAPEFILE'), ('https://visibleearth.nasa.gov/img/geotiff.png', 'GEOTIFF'), ('https://static.thenounproject.com/png/3962382-200.png', 'GEOJSON'), ('https://cdn-icons-png.flaticon.com/512/29/29058.png', 'TIFF'), ('https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Simple_Comic_7z.png/640px-Simple_Comic_7z.png', '7ZIP'), ('https://icons.iconarchive.com/icons/icons8/windows-8/512/Files-Png-icon.png', 'PNG'), ('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLPqd4e8xWKGB_J13hrARNidyJ6u2KzM5CHCX9CRWXYg&s', 'RAR FILE'), ('https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/PDF_icon.svg/1200px-PDF_icon.svg.png', 'PDF'), ('https://cdn-icons-png.flaticon.com/512/29/29620.png', 'GZ'), ('https://static.thenounproject.com/png/3180095-200.png', 'JPEG'), ('https://cdn-icons-png.flaticon.com/512/29/29264.png', 'JPG'), ('https://cdn-icons-png.flaticon.com/512/29/29528.png', 'KML')], default='', max_length=1000, verbose_name='Icon Url'),
        ),
    ]
