# Generated by Django 4.1.1 on 2022-11-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_gisdata_category_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_url',
            field=models.CharField(blank=True, default='https://gisdata-001.s3.amazonaws.com/media/default.webp', max_length=1000, null=True),
        ),
    ]
